#!/usr/bin/env ruby
require_relative "ruby/all"

experiment_name = ARGV[0]
concurrency = ARGV[1] || 2
one_generation = ARGV[2] == "one-generation"

if experiment_name.nil?
  puts "Name of experiment required as argument!"
  exit 1
end

exit(1) unless BuildDependencies.call

$stop_now = false
# The runner checks this flag between games; the games themselves get the
# same SIGINT from the terminal and stop.
trap('SIGINT') do
  puts 'Stopping ...'
  $stop_now = true
end

experiment_dir = "experiments/#{experiment_name}"

SetupExperiment.call(experiment_dir) do |settings|
  RunExperiment.call(settings.merge('concurrency' => concurrency, 'one_generation' => one_generation))
end
