name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - uses: jdx/mise-action@v4
    - name: Setup experiments
      run: mise run setup-experiments
    - name: Verify
      run: mise run verify
